name: CI

on: [push, pull_request]

jobs:
  test:
    name: test/node ${{matrix.node}}/${{matrix.platform}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: 16
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - run: yarn test
  coverage:
    needs: [test]
    name: test/coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: 16
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - run: yarn coverage
    - name: Run codacy coverage reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        coverage-reports: hook/coverage/lcov.info
