name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - run: yarn test
    - run: yarn coverage

    - name: Run codacy coverage reporter
      env:
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      if: env.CODACY_PROJECT_TOKEN != null
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        coverage-reports: hook/coverage/lcov.info
